'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Qdi.DataAccess.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MGSlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MGSlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mgs_qdi.qdi..
        '''</summary>
        Friend ReadOnly Property r_Basemap_Owner() As String
            Get
                Return ResourceManager.GetString("r_Basemap_Owner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.
        '''</summary>
        Friend ReadOnly Property r_dataEditorPassword() As String
            Get
                Return ResourceManager.GetString("r_dataEditorPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.
        '''</summary>
        Friend ReadOnly Property r_dataEditorUserName() As String
            Get
                Return ResourceManager.GetString("r_dataEditorUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.
        '''</summary>
        Friend ReadOnly Property r_dataViewerPassword() As String
            Get
                Return ResourceManager.GetString("r_dataViewerPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.
        '''</summary>
        Friend ReadOnly Property r_dataViewerUserName() As String
            Get
                Return ResourceManager.GetString("r_dataViewerUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STUDENT.
        '''</summary>
        Friend ReadOnly Property r_DefaultLogin() As String
            Get
                Return ResourceManager.GetString("r_DefaultLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend ReadOnly Property r_forceDebugMode() As String
            Get
                Return ResourceManager.GetString("r_forceDebugMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.
        '''</summary>
        Friend ReadOnly Property r_QDI_database() As String
            Get
                Return ResourceManager.GetString("r_QDI_database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.
        '''</summary>
        Friend ReadOnly Property r_QDI_database_debug() As String
            Get
                Return ResourceManager.GetString("r_QDI_database_debug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sde:postgresql:140.209.68.146.
        '''</summary>
        Friend ReadOnly Property r_QDI_instance() As String
            Get
                Return ResourceManager.GetString("r_QDI_instance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sde:postgresql:140.209.68.146.
        '''</summary>
        Friend ReadOnly Property r_QDI_instance_debug() As String
            Get
                Return ResourceManager.GetString("r_QDI_instance_debug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.qdi..
        '''</summary>
        Friend ReadOnly Property r_QDI_Owner() As String
            Get
                Return ResourceManager.GetString("r_QDI_Owner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qdi.qdi..
        '''</summary>
        Friend ReadOnly Property r_QDI_Owner_debug() As String
            Get
                Return ResourceManager.GetString("r_QDI_Owner_debug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to userid.
        '''</summary>
        Friend ReadOnly Property r_qduserfile_userid_field() As String
            Get
                Return ResourceManager.GetString("r_qduserfile_userid_field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to userright.
        '''</summary>
        Friend ReadOnly Property r_qduserfile_userright_field() As String
            Get
                Return ResourceManager.GetString("r_qduserfile_userright_field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to versionname.
        '''</summary>
        Friend ReadOnly Property r_qdversion_versionname_field() As String
            Get
                Return ResourceManager.GetString("r_qdversion_versionname_field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to versionnum.
        '''</summary>
        Friend ReadOnly Property r_qdversion_versionnum_field() As String
            Get
                Return ResourceManager.GetString("r_qdversion_versionnum_field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 140.209.68.146.
        '''</summary>
        Friend ReadOnly Property r_Server() As String
            Get
                Return ResourceManager.GetString("r_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend ReadOnly Property r_testMode() As String
            Get
                Return ResourceManager.GetString("r_testMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sde.DEFAULT.
        '''</summary>
        Friend ReadOnly Property r_Version() As String
            Get
                Return ResourceManager.GetString("r_Version", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
